### ISSUE TITLE
slack build failed template nullpointerexception

### ISSUE THREAD

**Issue by aaronjensen** [tcplugins/tcWebHooks#44]
```
[2016-08-18 13:14:32,218]   WARN - ildServer.util.EventDispatcher - Error in event handler: java.lang.NullPointerException 
java.lang.NullPointerException
	at webhook.teamcity.payload.format.WebHookPayloadJsonTemplate.getStatusAsString(WebHookPayloadJsonTemplate.java:43)
	at webhook.teamcity.payload.format.WebHookPayloadGeneric.buildFinished(WebHookPayloadGeneric.java:64)
	at webhook.teamcity.WebHookContentBuilder.buildWebHookContent(WebHookContentBuilder.java:78)
	at webhook.teamcity.WebHookListener.processBuildEvent(WebHookListener.java:78)
	at webhook.teamcity.WebHookListener.buildFinished(WebHookListener.java:138)
	at sun.reflect.GeneratedMethodAccessor337.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:121)
	at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.superDispatch(ServerSideEventDispatcher.java:6)
	at jetbrains.buildServer.serverSide.ServerSideEventDispatcher$1.run(ServerSideEventDispatcher.java:1)
	at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAs(SecurityContextImpl.java:3)
	at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAsSystem(SecurityContextImpl.java:11)
	at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.dispatch(ServerSideEventDispatcher.java:12)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:68)
	at com.sun.proxy.$Proxy19.buildFinished(Unknown Source)
	at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl.finishBuild(RunningBuildsManagerImpl.java:24)
	at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl.access$600(RunningBuildsManagerImpl.java:198)
	at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl$5.run(RunningBuildsManagerImpl.java:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by netwolfuk** [comment]
Can I get some more detail on this? Like example config files.

**Comment by aaronjensen** [comment]
Here is this:

`# cat pluginData/plugin-settings.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings>
  <webhooks enabled="true">
    <webhook url="https://hooks.slack.com/services/xxxxxxx" enabled="true" format="jsontemplate" template="slack.com">
      <states>
        <state type="buildBroken" enabled="false" />
        <state type="changesLoaded" enabled="false" />
        <state type="buildInterrupted" enabled="false" />
        <state type="buildFixed" enabled="false" />
        <state type="buildFinished" enabled="true" />
        <state type="buildStarted" enabled="false" />
        <state type="responsibilityChanged" enabled="false" />
        <state type="buildSuccessful" enabled="true" />
        <state type="buildFailed" enabled="true" />
        <state type="beforeBuildFinish" enabled="false" />
      </states>
      <build-types enabled-for-all="true" enabled-for-subprojects="true" />
    </webhook>
  </webhooks>
</settings>
```

Are there any other config files that would be helpful? If it helps I'm on TC 10.0.1

**Comment by aaronjensen** [comment]
So I was able to fix it by fixing another thing that was bothering me. By VCS config had an unnecessary branch spec. When I cleared the branch spec (it was just to make the long branch name shorter) then it all works.

![the-link-merge vcs root settings diff teamcity 2016-08-18 13-57-10](https://cloud.githubusercontent.com/assets/8588/17790538/bb521b0c-654b-11e6-9f9f-4df7f09c6b0c.png)

**Comment by netwolfuk** [comment]
Hmm, interesting. I've not played with branchSpec before. I'll leave this issue open, but low priority.

**Comment by netwolfuk** [comment]
Also, @mmalvik, are you using branchSpec too?

**Comment by mmalvik** [comment]
Looks like we are 1.1.-alpha7.122.138

![tcwebhooks](https://user-images.githubusercontent.com/1527808/45683846-e6d9be00-bb44-11e8-8a2d-3887bfa41bfc.png)

Looks like we are 2 years behind... 😅
You think an update might fix it?

Yes, we have branch spec set to **+:refs/heads/***

**Comment by netwolfuk** [comment]
Oh, that branchSpec should be fine. I use that one all the time too.

I haven't done anything specific to fix this issue, but I would recommend updating as there are many many bug fixes and improvements.

**Comment by netwolfuk** [comment]
Btw. Looking at the stack trace, I'm not convinced you're seeing the same issue as Aaron was. Please do update, let me know if you see the issue again.

**Comment by netwolfuk** [comment]
Sorry, bumping this to 1.3
